#if !defined(__CONST_H)
#define __CONST_H

const int STRLEN = 80;
const int NVLEN = 25;
const int NASJONLEN = 3;
const int MAXNASJONER = 200;
const int MAXOVELSER = 20;
const int MINDELTAGERE = 2;
const int MAXDELTAGERE = 100;		// Consten star i opp.text. men riktig verdi er ukjent. Satt tilfeldig til 100. 
const int ANTALLVINNERE = 7;		// Avgjoor hvor mange nasjoner som faar poeng.

#endif
