#if !defined(__DELTAGERE_H)
#define  __DELTAGERE_H
/*
class Lege : public TextElement		//	Lege arver fra TextElement.
{
private:
	char* adresse;					//	Tar var p^ adressen og
	int  telefon;					//	telefonnummeret til legen.
	List* reseptListe;				//	Teller resepter.

public:
	Lege(char* t);					//	Constructor for manuell innskriving.
	Lege(char ch[], ifstream &fil);	//	Constructor for innhenting fra fil.
	~Lege();						//	Deconstructor(Sletter alle 'new').
	void lagResept();
	void display();
	void skrivTilFil(ofstream &fil);
	void finnPasient(char ch[]);
	int slettResept(int i);
};
*/
#endif